### ISSUE TITLE
Lab 1 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3851-Fall2019/lab1-CarterAlex3#1]
@CarterAlex3 

Lines 162-167 in your Rmd doc are not quite right....need hyperlinked Figure, and the correct second footnote.

Should use something similar to:

To display the saved file as shown in Figure \@ref(fig:ig), use the `include_graphics()` function from knitr.^[Use the argument dpi = 96 inside include_graphics().]

with the following code chunk:

```{r, label = "ig", echo = FALSE, fig.cap = "Using knitr::include_graphics()"}
knitr::include_graphics("./JPG/YourFileName.jpeg", dpi = 96)
```

The rest looks great.

**Comment by alanarnholt** [comment]
Code chunk will look something like: 

```{r, label = "ig", echo = FALSE, fig.cap = "Using knitr::include_graphics()"}

note we are not using html to center the fig.cap.

**Comment by alanarnholt** [comment]
Having issues getting the code chunk to display properly:

{r, label = "ig", echo = FALSE, fig.cap = "Using knitr::include_graphics()"}
knitr::include_graphics("./JPG/YourFileName.jpeg", dpi = 96)

**Comment by CarterAlex3** [comment]
@alanarnholt

**Comment by CarterAlex3** [comment]
@alanarnholt I fixed the problems on RStudio and knitted. The html on RStudio is correct but when clicking the link on github to view it, the problems are still there. I committed and pushed.

**Comment by alanarnholt** [comment]
@CarterAlex3 Line 162 of your Rmd doc still has the incorrect footnote...you have two footnotes that say the same thing.  Please stop by if you need assistance.

**Comment by CarterAlex3** [comment]
@alanarnholt
